version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./healthcare_inventory.db
      - KNOT_API_KEY=${KNOT_API_KEY:-demo_key}
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY:-demo_key}
    volumes:
      - ./data:/app/data
      - ./backend/models:/app/models
    networks:
      - healthcare-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - healthcare-net

networks:
  healthcare-net:
    driver: bridge